Slash encoding for Apache
monsieurbiz/SyliusSearchPlugin pull request #212
Opened 2024-07-03 15:00 UTC by etienne-monsieurbiz

### Features

- Avoid double encoding when applying filters
- Replace the `%2F` by a `/` when submitting the search form because the `%2F` is provoking a 404 page when it is present in the URL on a Apache WebServer with the Directive `AllowEncodedSlashes` at `false`
https://httpd.apache.org/docs/current/mod/core.html#allowencodedslashes

### Info

The error is not reproductible on local with symfony server

### Error on Apache

![Capture d’écran 2024-07-03 à 16 57 01](https://github.com/monsieurbiz/SyliusSearchPlugin/assets/111362284/2d269916-19e7-4146-b1c7-0fd97842b5fb)

### Demo (Not `%2F` in url when adding a `/` in search)

https://github.com/monsieurbiz/SyliusSearchPlugin/assets/111362284/229c2662-e9da-47db-8fca-0b7dd019529d

2024-07-03 15:07 UTC, delyriand approved these changes

2024-07-03 15:43 UTC, maximehuran requested changes

2024-07-03 15:43 UTC, maximehuran commented on .github/workflows/recipe.yaml
>        SYMFONY_ENDPOINT: http://127.0.0.1/
Remove that

2024-07-04 07:36 UTC, maximehuran approved these changes

2024-07-04 07:37 UTC, merged