fix typo in readme
monsieurbiz/SyliusSearchPlugin pull request #88
Opened 2021-04-16 08:07 UTC by oallain

2021-04-16 11:29 UTC, jacquesbh requested changes

2021-04-16 11:29 UTC, jacquesbh commented on README.md
> +Indexed documents are all entities defined in `monsieur_biz_search.documentable_classes` who implements `DocumentableInterface`.
```suggestion
Indexed documents are all entities defined in `monsieur_biz_search.documentable_classes` which implements `DocumentableInterface`.
```

🤪

2021-04-17 18:07 UTC, oallain commented on README.md
> +Indexed documents are all entities defined in `monsieur_biz_search.documentable_classes` who implements `DocumentableInterface`.
Yes, it's better :D

2021-04-17 22:54 UTC, jacquesbh approved these changes

2021-04-17 22:54 UTC, merged

2021-04-17 22:54 UTC, jacquesbh commented
Thank you @oallain !